---
- name: Create Packer template file
  hosts: local
  vars_files:
    - vm_data/howler_packer_template.yml
  tasks:
    - name: "Create preseed template"
      template:
        src: "vm_data/{{ hostname }}_preseed_template.j2"
        dest: "public_http/{{ fqdn }}.preseed"

    - name: "Calculate md5 of preseed file"
      stat:
        path: "public_http/{{ fqdn }}.preseed"
        get_md5: yes
      register: generated_preseed

    - name: "Create Packer template"
      template:
        src: "templates/packer_template.json.j2"
        dest: "packer_templates/{{ fqdn }}.json"

    - name: "Validate packer template"
      command: "packer validate ./packer_templates/{{ fqdn }}.json"

    - name: "Build packer template"
      command: "packer build ./packer_templates/{{ fqdn }}.json"
      when: no
